#!/bin/bash

# Название виртуального окружения
SCRIPT_DIR=$(dirname "$0")
VENV_DIR="$SCRIPT_DIR/venv"

# Убедимся, что система обновлена и установим Python
install_python() {
    if ! command -v python3 &> /dev/null; then
        echo "Python3 не найден. Устанавливаем..."
        sudo apt update
        sudo apt install -y python3 python3-venv python3-pip
    fi
}

# Создание виртуального окружения и установка зависимостей
setup_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        echo "Виртуальное окружение не найдено. Создаём..."
        python3 -m venv "$VENV_DIR"
        if [ $? -ne 0 ]; then
            echo "Ошибка при создании виртуального окружения."
            exit 1
        fi

        source "$VENV_DIR/bin/activate"
        # Установим зависимости, если файл requirements.txt существует
        if [ -f "$SCRIPT_DIR/requirements.txt" ]; then
            pip install --upgrade pip
            pip install -r "$SCRIPT_DIR/requirements.txt"
        else
            echo "Файл requirements.txt не найден. Пропускаем установку зависимостей."
        fi
        deactivate
    fi
}

# Запуск Python скрипта
run_script() {
    # logo - вывод логотипа "OCMU"
    echo "OCMU - OpenCart Modules Utility"
    source "$VENV_DIR/bin/activate"
    python3 "$SCRIPT_DIR/oc-module.py" "${@:-help}"
    deactivate
}

# Основной блок
install_python
setup_venv
run_script "$@"
