#!/bin/bash

# Директория скрипта
SCRIPT_DIR=$(dirname "$0")

# Проверка наличия PHP
install_php() {
    if ! command -v php &> /dev/null; then
        echo "PHP не найден. Устанавливаем..."
        sudo apt update
        sudo apt install -y php php-cli php-json
        
        # Проверка успешности установки PHP
        if ! command -v php &> /dev/null; then
            echo "Не удалось установить PHP. Пожалуйста, установите PHP вручную."
            exit 1
        fi
    fi
}

# Проверка необходимых PHP расширений
check_php_extensions() {
    local required_extensions=("json" "fileinfo" "zip")
    local missing_extensions=()

    for ext in "${required_extensions[@]}"; do
        if ! php -r "exit(extension_loaded('$ext') ? 0 : 1);"; then
            missing_extensions+=("$ext")
        fi
    done

    if [ ${#missing_extensions[@]} -gt 0 ]; then
        echo "Отсутствуют необходимые расширения PHP: ${missing_extensions[*]}"
        echo "Устанавливаем..."
        sudo apt update
        for ext in "${missing_extensions[@]}"; do
            sudo apt install -y php-$ext
        done
    fi
}

# Запуск PHP скрипта
run_script() {
    # Вывод логотипа "OCMU"
    echo "OCMU - OpenCart Modules Utility (PHP)"
    
    # Определяем путь к основному скрипту
    # Если запускаем из установленного пакета
    if [ -f "/usr/share/oc-module-manage/oc-module.php" ]; then
        PHP_SCRIPT="/usr/share/oc-module-manage/oc-module.php"
    # Если запускаем из директории разработки
    elif [ -f "$SCRIPT_DIR/oc-module.php" ]; then
        PHP_SCRIPT="$SCRIPT_DIR/oc-module.php"
    else
        echo "Ошибка: не найден файл oc-module.php"
        exit 1
    fi
    
    # Сделаем скрипт исполняемым, если он еще не исполняемый
    if [ ! -x "$PHP_SCRIPT" ]; then
        chmod +x "$PHP_SCRIPT"
    fi
    
    # Запуск PHP скрипта с передачей всех аргументов
    php "$PHP_SCRIPT" "$@"
}

# Основной блок
install_php
check_php_extensions
run_script "$@"
